# Generated by Django 3.1.4 on 2023-01-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='r1', max_length=20)),
                ('model_size', models.TextField(max_length=200)),
                ('model_battery', models.IntegerField(default=0, null=True)),
                ('model_weight', models.IntegerField(default=0, null=True)),
                ('model_firmware', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mycar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycar_speed', models.IntegerField(default=0, null=True)),
                ('mycar_battery', models.IntegerField(default=0, null=True)),
                ('mycar_color', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.CASCADE, to='omorobot.user')),
            ],
        ),
    ]
